---
swagger: "2.0"
info:
  description: This proxy api returns an available list of in-app notifications available by country and sourceApp
  version: 1.0.0
  title: CAPI In-App Notifications api
  contact:
    email: mgocapi@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: consumerapi.moneygram.com
basePath: /services/capi/api/v1
schemes:
- https
parameters:
  clientKeyParam:
    name: clientkey
    in: header
    required: true
    type: string
  localHeaderParam:
    name: locale-header
    in: header
    required: true
    type: string
  authParam:
    name: auth
    in: header
    required: true
    type: string
    description: Bearer token
paths:
  /notification/inApp:
    get:
      summary: retrieve unauthed in-app notifications
      description: retrieve country based unauthed in-app notifications
      operationId: getUnAuthedInAppNotifications
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/clientKeyParam'
      - $ref: '#/parameters/localHeaderParam'
      responses:
        "200":
          description: a list of in-app notifications available for the given country and sourceApp derived from the locale-header and clientkey
          schema:
            type: array
            items:
              $ref: '#/definitions/InAppNotification'
        "400":
          description: bad request
        "500":
          description: internal error, need to include downstream service error if present
    post:
      summary: retrieve authed in-app notifications
      description: retrieve country based authed in-app notifications
      operationId: getAuthedInAppNotifications
      consumes:
      - application/json      
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/clientKeyParam'
      - $ref: '#/parameters/localHeaderParam'
      - $ref: '#/parameters/authParam'
      responses:
        "200":
          description: a list of in-app notifications available for the given country and sourceApp derived from the locale-header and clientkey, we can also use the profile lang preference to provide the correct localized content
          schema:
            type: array
            items:
              $ref: '#/definitions/InAppNotification'
        "400":
          description: bad request
        "500":
          description: internal error, need to include downstream service error if present
definitions:
  InAppNotification:
    type: object
    properties:
      name:
        type: string
        description: name of the notification
        example: referralSenderPromoReminder
      priority:
        type: integer
        description: 0 being the highest priority
        example: 0
      allowNext:
        type: boolean
        description: this indicates whether a lower priority notification should be allowed to show after this one
        example: false
      acknowledgementRequired:
        type: boolean
        description: this indicates whether the notification requires the user acknowledgement
        example: true        
      displayPolicy:
        type: string
        description: this will be used by application to determine the time to live of the notification
        enum: [ONCE,ALWAYS]        
      format:
        type: string
        description: this defines the format of notification
        enum: [TOAST,POPUP]        
      epic:
        type: string
        description: name of the flow
        enum: [AUTHHOME,UNAUTHHOME,SENDMONEY,BILLPAY,RECEIVEMONEY]
      contentUrl:
        type: string
        description: url to the notification html content
        example: full s3 bucket path
  InAppNotificationConfiguration:
    allOf: 
      - $ref: '#/definitions/InAppNotification'
      - type: object
        properties:
          relatedFeatureToggleSwitchName:
            type: string
            description: name of the feature toggle switch, this is to be used to find out whether the feature in turned on/off in country config
            example: toggle-referralProgram
          sourceApp:
            type: string
            description: POE type
            enum: [WEB,IOS,ANDROID]
    