---
swagger: "2.0"
info:
  description: This proxy api returns an available list of in-app notification configs filtered by country and sourceApp
  version: 1.0.0
  title: CAPI In-App Notification Config API
  contact:
    email: mgocapi@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /mgocapi/InAppNotificationConfigProxy/1.0.0
schemes:
- https
paths:
  /config/inAppNotification:
    get:
      summary: retrieve the in-app notification config
      description: To retrieve country based in-app notification confi.
      operationId: getInAppNotificationConfig
      produces:
      - application/json
      parameters:
      - name: clientKey
        in: header
        required: true
        type: string
      - name: locale-header
        in: header
        required: true
        type: string
      responses:
        "200":
          description: a list of in-app notification configs available for the given country and sourceApp indicated by the locale-header and clientkey
          schema:
            type: array
            items:
              $ref: '#/definitions/InAppNotificationConfig'
        "400":
          description: bad request
        "500":
          description: internal error, need to include downstream service error if present
definitions:
  InAppNotificationConfig:
    type: object
    properties:
      name:
        type: string
        example: referralSenderPromoPending
      priority:
        type: integer
        example: 0
        description: 0 being the highest priority
      logInRequired:
        type: boolean
        example: true
        description: this indicates whether the notification can be presented before or after user logs in
      allowNext:
        type: boolean
        example: false
        description: this indicates whether a lower priority notification should be allowed to show after this one
      blocking:
        type: boolean
        example: true
        description: this indicates whether the notification requires user action to dismiss
      displayPolicy:
        type: string
        example: ONCE/ALWAYS
        description: this will be used by application to determine the time to live of the notification
      format:
        type: string
        example: TOAST/POPUP
        description: this defines the format of notification
parameters:
  clientKeyParam:
    name: clientKey
    in: header
    required: true
    type: string
  localHeaderParam:
    name: locale-header
    in: header
    required: true
    type: string
